server:
  address: localhost
  port: 9090

spring:
#  sql:
#    init:
#      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
#      change this to update to migrate
      ddl-auto: update
    defer-datasource-initialization: true

  flyway:
#    baseline-on-migrate: true
    enabled: false