server:
  address: localhost
  port: 9090

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/cydeo
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

#  flyway:
#    baseline-on-migrate: true
#    enabled: false