server:
  address: localhost
  port: 8082

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  main:
    allow-circular-references: true

keycloak:
  realm: cydeo-dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: training
  credentials:
    secret: bVMboQbDPO585LnaVuPL2rLT0fG37qGS
  use-resource-role-mappings: true
  bearer-only: true
